### ISSUE TITLE
Erweiterungen Mit Anmeldungen nur aus der Schweiz

### ISSUE THREAD

**Issue by StanBarrows** [medical-informatics/application#68]
- [x] Erweiterung Land [Default Disabled] mit Begleittext: Aktuell sind nur Registrierungen aus der Schweiz möglich

![image](https://user-images.githubusercontent.com/10268813/76805437-11124780-67df-11ea-8bb0-1cf4b0dffcc2.png)

**Comment by SuddenlyRust** [comment]
Landfeld hinzugefügt mit Hinweis.

Ich hab es mal nicht disabled gemacht, weil es sonst nicht an den Server geschickt wird im Formular und ich hab Validierung im Backend schon auf das Feld gesetzt.

![image](https://user-images.githubusercontent.com/14092921/76892868-a2d78e80-688b-11ea-932d-cbf606d57136.png)
