### ISSUE TITLE
Checkbox Datenschutz

### ISSUE THREAD

**Issue by StanBarrows** [medical-informatics/application#83]
- [ ] Checkbox & Referenz zum Datenschutz

Mit dem Absenden des Formular erklären Sie sich mit unseren Datenschutz regeln einverstanden.

![image](https://user-images.githubusercontent.com/10268813/76803109-62b7d380-67d9-11ea-89e1-2cb084717703.png)

**Comment by SuddenlyRust** [comment]
Wir sollten vielleicht Absenden Button nach links verschieben. Was denkst? 

![image](https://user-images.githubusercontent.com/14092921/76896162-9eae6f80-6891-11ea-80ff-45029f89fccc.png)

**Comment by StanBarrows** [comment]
Evtl. ein zusätzliche Komponente im Stiel von den anderen Boxen?

**Comment by SuddenlyRust** [comment]
Super Idee. Passt nun viel besser 

![image](https://user-images.githubusercontent.com/14092921/76897737-9572d200-6894-11ea-9ccd-2cc6c05044a4.png)
