### ISSUE TITLE
Hilfetext Handy-Nr.

### ISSUE THREAD

**Issue by StanBarrows** [medical-informatics/application#84]
- [ ] Hilfetext - Aktuell sind nur Handy-Nummern aus der Schweiz möglich

![image](https://user-images.githubusercontent.com/10268813/76844689-f3c09600-683d-11ea-8d19-50e47c3a0a2b.png)

**Comment by SuddenlyRust** [comment]
Hilfetext hinzugefügt.

![image](https://user-images.githubusercontent.com/14092921/76896866-f3061f00-6892-11ea-8dba-a4bb970082e2.png)
